### ISSUE TITLE
This application could not be started

### ISSUE THREAD

**Issue by Jimadine** [kizzx2/cmd-recycle#1]
Hi,

When I drop recycle-v0.2.exe into the system32 folder and run it from a command shell I get an error:

**recycle-v0.2.exe - This application could not be started.**

**This application could not be started.**

**Do you want to view information about this issue?**

**Yes   No**

I'm then led to http://support.microsoft.com/kb/2715633 which tells me the following:

_Error message_
_This application could not be started._
_Cause_
_The app is not configured in a way that makes it possible to determine the appropriate version of the .NET Framework runtime. The corresponding shim code is SHIM_NOVERSION_FOUND._
_Resolution_
_You can't fix the configuration problem yourself. Contact the app vendor to resolve the issue._

cmd-recycle works fine in e.g. a regular (non-system) folder. Is this a known issue? I've replicated this on two Windows 7 x64 systems. Strangely it's not an issue on a Windows 7 VM I downloaded from http://modern.ie. This machine has Microsoft .NET Framework 4 Client Profile installed, while the two affected machines have a Microsoft .NET framework 4.5.2. I don't know if that's significant.

Thanks!

**Comment by kizzx2** [comment]
@Jimadine try putting it in `SysWOW64`?

This is quite strange. I don't have a Windows machine handy these days to debug it :P But I guess if you just want to be able to launch it from command line you can [add the installation path to `%PATH%` instead](http://www.computerhope.com/issues/ch000549.htm)

**Comment by Jimadine** [comment]
Thanks for the reply. SysWOW64 isn't in my PATH (though I realise I could add it). I generally like to drop my third party exes into system32 as it saves adding extras paths to my PATH. Not a problem really, it's probably something specific to the machines that's breaking it. If I work it out I'll add a comment, as it's possible others have hit this issue too.
