### ISSUE TITLE
Only runs on .NET 3.5

### ISSUE THREAD

**Issue by user8446** [kizzx2/cmd-recycle#2]
Thank you for this. However, it would only run on the very old .NET 3.5 and also although working throws this error:

/recycle - Error: System.IO.FileNotFoundException

**Comment by kizzx2** [comment]
I just tested this on some version of Windows that I found (Version 1903 (OS Build 18362.418)) and it seems to run fine (which has .NET v3.5 installed)

What's your system config and what's the exact command that you ran?

**Comment by user8446** [comment]
Hi, meaning I'm on a newer version of .NET and I had to install 3.5 for it to run. OS is 1909 build 18363.476.

Command used:

`C:"\Users\MyPath\recycle-v0.2.exe" /recycle "C:\Users\MyPath\Documents\MyFolder\*.pdf"`

**Comment by kizzx2** [comment]
`/recycle` is not necessary. In your case the correct command should be:

```
"C:\Users\MyPath\recycle-v0.2.exe" "C:\Users\MyPath\Documents\MyFolder\*.pdf"
```

**Comment by user8446** [comment]
Thank you, that does clear that error
